# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: true
- task: PublishBuildArtifacts@1

- checkout: self
  submodules: true
- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    api_location: 'api'
    output_location: '/src'
    azure_static_web_apps_api_token: "f1dcbf3b64db6c9173d7f33956e6ab9fa6a041355c77531461f7080cf287a1784-486b5dd7-42dc-4fae-9da7-8fb95baf7c82003322328"